jamesmunns/postcard

Cargo.toml, src/error.rs
Previously, using Postcard in a project that also uses std-enabled Serde did not work.
```toml
[dependencies]
serde = "1.0" # only works if we add default-features=false
postcard = "0.4"
```
```console
error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
--> postcard-0.4.0/src/error.rs:71:6
|
71 | impl serde::ser::Error for Error {
|      ^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `error::Error`
```
This PR makes Postcard compile whether or not Serde std is enabled.
=> Support using with std-enabled serde

src/lib.rs, src/ser/flavors.rs, src/ser/mod.rs
This PR does two things:
1. Make the inner type of `StdVec` pub, so that it can be created
manually outside of `postcard`.
2. Add `to_stdvec` and `to_stdvec_cobs` utility functions, to make it
easier to directly serialise to these flavours
I also added doc tests, one of which fails which is a bit
strange. It's basically the same example as the `to_vec_cobs` doc
test. And I don't assume that the `std::vec::Vec<u8>` would handle
bytes drastically different from `heapless::Vec`...right? Anyway,
maybe you have some ideas there.
=> Improvements to serialisation with `StdVec` for `use-std` feature

src/de/deserializer.rs, src/ser/serializer.rs
This crate serializes the data in binary format, which is not human readable.
Ref: https://docs.serde.rs/serde/trait.Serializer.html#method.is_human_readable
=> mark serializer/deserializer as not human readable

src/error.rs
We could easily derive `Copy` too, but I figured that it might be
desirable at some point to add non-Copy fields to a variant, which then
would be a breaking change.
=> Derive `Clone` for `Error`

src/de/deserializer.rs, src/de/mod.rs, src/ser/mod.rs, src/ser/serializer.rs, tests/loopback.rs
This is mainly used in conjunction with `alloc::BTreeMap`.
=> support map

Cargo.toml, src/de/deserializer.rs, src/de/mod.rs, src/ser/flavors.rs, src/ser/mod.rs, src/ser/serializer.rs, src/varint.rs, tests/loopback.rs
Serializer::serialize_bytes does not write the buffer size when
serializing, preventing deserialization from working properly when
serializing types that make use of this method (e.g. Bytes and BytesMut
from the bytes crate, CStr and CString from std::ffi). Simply adding the
missing size serialization breaks all size prefix serialization, as size
prefix serialization uses the existing Serializer::serialize_bytes
implementation to write the VarintUsize bytes to the output flavor.
This commit adds a try_push_varint_usize method to the SerFlavor trait
for writing out the encoded VarintUsize bytes, replacing all
VarintUsize::serialize calls with the SerFlavor method call, and adds
the same call to Serializer::serialize_bytes to ensure the size prefix
is now properly written. The …
=> Add missing size prefix for serialize_bytes

Cargo.toml
I'm playing around with `postcard` on an custom target that doesn't support CAS. Luckily, `heapless` already includes a `cas` feature flag!
This PR adds a new enabled-by-default `heapless-cas` feature which corresponds to the `heapless/cas` feature.
=> Add `heapless-cas` feature (enabled by default)

Cargo.toml
There was an unsoundness issue in heapless, making RustSec news: https://github.com/japaric/heapless/issues/181.
This is fixed in heapless 0.6.1.
The semver bump here is due to heapless 0.6 bumping generic-array to 0.14, which is useful in and of itself.
Think you can cut a release?
=> Bump heapless, fixing unsoundness issue

README.md
it took me  a bit of googling to figure out how to depend on `serde` correctly so I thought I'd add this to the docs :)
=> README: add hint about no-std serde deps

src/de/deserializer.rs
Adds some more doc to the deserializer noting that postcard [is non-self-describing](https://github.com/jamesmunns/postcard/blob/main/src/de/deserializer.rs#L207). My hope is that this will help others avoid any surprises.
=> Clarify the non-self-describing nature of postcard

src/lib.rs, src/varint.rs
This PR adds a `Fixint<T>` that forces integers to be serialized as a fixed-size array.
=> Fixint wrapper type.

src/varint.rs
This PR optimizes the `varint_*` functions to avoid an unnecessary bit masking.
The idea behind this PR is the following:
- Iteration stops if `(value >>= 7) == 0`, in which case `value < 128`. In this case, the `0x7F` masking isn't necessary.
- If `value > 128` we want to set the highest bit of the extracted byte to 1. In this case, the `0x7F` masking isn't necessary, because we overwrite the masked bit anyway.
Assuming I'm not catastrophically wrong, the resulting code optimizes slightly better: https://rust.godbolt.org/z/8dz48vocx
=> Optimize Varint encoding

Cargo.toml, postcard-derive/Cargo.toml, postcard-derive/src/lib.rs, src/lib.rs, src/ser/max_size.rs, src/ser/mod.rs, tests/max_size.rs
This adds a trait `MaxSize`:
```rust
pub trait MaxSize {
/// The maximum possible size that the serialization of this
/// type can have, in bytes.
const POSTCARD_MAX_SIZE: usize;
}
```
and a derive macro that implements it for structs and enums.
I think this just needs a little more documentation and then it'll be ready to merge. I would like someone else to double check my logic for computing the varint size though.
The naming needs a little more work too. I'm not super happy with the trait and constant name.
=> Add a `MaxSize` trait and derive macro

postcard-derive/src/lib.rs, postcard-derive/src/schema.rs, src/lib.rs
This allows Schema derive to be used by external crates
=> Fix Schema proc_macro to export through public experimental module.

src/de/deserializer.rs
For example, the ATmega328P I'm using right now has an 8-bit architecture. It seems this change is all that's needed to make postcard work on that MC, but I'll add a comment once I actually tried it out.
=> Add support for 16-bit and 8-bit architectures

src/fixint.rs, src/lib.rs
This changes the (thankfully not public, by shear accident), `fixint` module to be usable through the `#[serde(with = ...)]` field attribute instead of wrappers. 
For example:
```rust
#[derive(Serialize, Deserialize)]
pub struct DefinitelyBE {
#[serde(with = "crate::fixint::be")]
x: u16,
}
```
=> Make fixints usable through serde field attributes instead of wrappers

src/schema.rs
Hi, we found a use for `Schema` in an `std` context, and the non-`heapless` String impl was missing.
Would you be okay with adding this impl?
BTW, I find that that this experimental feature is useful for `serde` in general, not just for postcard use.
=> Add a Schema impl for `std::string::String` with the `use-std` feature and for `alloc::string::String` with `alloc`

Cargo.toml, postcard-derive/Cargo.toml
I forgot to bump the derive crate version :(
Issue #73 isn't fixed for crates.io downloads without this.
=> Bump postcard-derive version

src/de/deserializer.rs, src/varint.rs
It's not necessary to update a check value in every cycle - it's only relevant while processing the last encoded byte.
Obligatory godbolt link, this time with x86 asm because I was lazy: https://rust.godbolt.org/z/hMh3qW67h
=> Optimize varint decode

src/max_size.rs
If PhantomData<T> is being used, it's very likely that the T isn't included in the data, and thus the MaxSize for it does not need to be derived.
=> PhantomData's T doesn't need MaxSize impl

src/accumulator.rs
Currently there is an off-by-one error in bounds checking which may lead to `panic!` in `self.extend_unchecked()`. 
When calling:
```rust
let (take, release) = input.split_at(n + 1);
```
the `take` slice has length of `n + 1` ([slice::split_at](https://doc.rust-lang.org/std/primitive.slice.html#method.split_at)), but currently the `if` condition checks for size `n`. 
I added a test case that demonstrates the issue using `CobsAccumulator<11>` and feeding it with a 12-byte message. Without the fix this will panic:
```
thread 'accumulator::extend_unchecked_in_bounds_test' panicked at 'range end index 12 out of range for slice of length 11', library/core/src/slice/index.rs:73:5
```
=> fix: cobs accumulator out-of-bounds index when data is 1 byte too long

src/de/mod.rs
I believe that the modification of the input buffer by the cobs decoding functions is not expected as a user of the library, as it requires you to copy the input buffer every time you call it. In postcard, this does not happen with the non-cobs serde functions. 
I consider that by noting this fact in the documentation, other users might be able to realise it earlier and spend less time debugging as it happened to me.
=> improved documentation of the cobs decoding

.gitignore, Cargo.toml, src/de/flavors.rs, src/de/mod.rs, src/lib.rs, src/ser/flavors.rs, src/ser/mod.rs, tests/crc.rs
A `crc` feature has been added that brings in the `crc` crate and a new `CrcModifier` flavour. This modifier flavour is similar to the COBS implementation in how it wraps another flavour.
Convenience functions for serde are also introduced.
TODO:
=> Introduces CRCs

src/de/mod.rs, src/ser/mod.rs
=> Format with rustfmt to eliminate trailing whitespaces

src/de/mod.rs, src/ser/mod.rs
This supercedes #106, with an additional fix of merge conflicts caused by merging #104 first.
Thanks @dtolnay!
=> Fix documentation of re-exports that have dedicated doc comment

Cargo.toml, src/de/flavors.rs, src/de/mod.rs, src/lib.rs, src/max_size.rs, src/schema.rs, src/ser/flavors.rs, src/ser/mod.rs
=> Render cfg information on docs.rs

src/varint.rs
I was reading through the varint implementation in postcard to sanity-check one of my own implementations, and I spotted a mistake in the code that calculates the maximum number of varint bytes an integer datatype can take.
The old version adds 7 instead of 6, so instead of the behaviour documented in the comment it would overestimate the number of varint bytes required by one for datatypes whole size is a multiple of 7 bits. Since there are thankfully none among the common integer datatypes, the behaviour is correct both before and after the change.
=> Minor: Fix off-by-one in varint size calculation

Cargo.toml, src/de/flavors.rs, src/de/mod.rs, src/lib.rs, src/ser/flavors.rs, src/ser/mod.rs, tests/loopback.rs
Added IO support using `embedded-io` and also supports std after #27. It does requires the user to pass a buffer for memory. Serialization uses `embedded-io` compatibility layer while deserialization reimplements it since I encountered lifetime issues
Couple points that I'm not sure with this implementation
- I'm not sure if it's `DeserializeUnexpectedEnd` is the right error to return when the IO fails, should an new internal error be created and used instead?
- Currently the pop function doesn't consume a byte on the provided buffer, is this an issue?
Comments are always appreciated!
=> Feat: Add IO traits support

Cargo.toml, src/de/flavors.rs, src/de/mod.rs, src/eio.rs, src/lib.rs, src/ser/flavors.rs, src/ser/mod.rs, tests/loopback.rs
This adds a new `embedded-io-06`  feature which allows users to use the latest `embedded_io` v `0.6.*`.
Backwards compatibility is maintained with the previous `embedded-io` which is now setup to activate the `embedded-io-04` feature internally.
=> #118 Add support for latest embedded-io

src/de/deserializer.rs, src/de/flavors.rs, src/de/mod.rs
Fixes and implements the changes suggested in #135.
=> Fix Vec pre-alloc panic 

postcard-derive/src/schema.rs, src/lib.rs, src/schema.rs, src/ser/mod.rs, src/ser/serializer.rs, tests/schema.rs
Here comes a 4-commit sandwich.
The actual issue I believe is fixed with this. However, there are 2 open questions regarding the schema tests (see commit message bodies):
* Where should the schema tests be located? As of now, they force the schema module to be `pub`lic because they are integration tests. A doc comment above `mod schema;` explicitly says not to make experimental features `pub` :laughing:
* The test for struct serialization does not pass. It seems it wants the array member to be schematized as a `Seq`, but the array member is schematized as a 10-element `Tuple`.
Let me know what you think :) I love using this crate.
=> Fix #89: `#[derive(Schema)]` for `StructVariant`s

src/ser/flavors.rs, src/ser/mod.rs, tests/crc.rs
The CRC digest lifetime is set to the same as the provided buffer lifetime which means that the CRC has to live as long as the buffer which I don't think is necessary as the `finalize()` method is called on the digest. This strictness of the lifetime meant that I couldn't create a `Crc` in the local scope i.e. a method and then just return the bytes (see the new unit test for an example of what I mean).
Clippy suggests this change and to remove a few other lifetimes too so I think this should be a low risk change :slightly_smiling_face:
Thanks for the great crate!
=> Remove unnecessary lifetimes of CRC digest

src/max_size.rs
```sh
RUSTFLAGS='--check-cfg=cfg(doc_cfg)' cargo check --features=alloc,experimental-derive
```
Note that with a continuous integration, this would probably not happen, see #144.
=> Fix compilation with alloc and experimental-derive

Cargo.toml, src/de/flavors.rs, src/de/mod.rs, src/lib.rs, src/max_size.rs, src/schema.rs, src/ser/flavors.rs, src/ser/mod.rs
See https://github.com/rust-lang/cargo/pull/13383 for the PR adding support.
Without this change, there are many warnings about https://blog.rust-lang.org/2024/05/06/check-cfg.html when compiling.
=> Use well-known docsrs cfg for docs.rs

.github/workflows/ci.yml, ci.sh
Note that the `ubuntu` GitHub Actions could/should be added as a required status check to pass for the `main` branch (this is configured in the repository settings under Rules with a Ruleset for the main branch).
Fixes #144
=> Add basic continuous integration script

ci.sh, src/accumulator.rs, src/de/deserializer.rs, src/de/flavors.rs, src/de/mod.rs, src/lib.rs, src/max_size.rs, src/ser/mod.rs, src/ser/serializer.rs, tests/accumulator.rs, tests/crc.rs, tests/loopback.rs, tests/schema.rs
I tried to choose the most obvious fix for each warning, but sometimes it might be arguable. I'll try to point out those cases. Feel free to suggest alternatives if needed.
=> Fix clippy lints

source/postcard/Cargo.toml
See https://github.com/jamesmunns/postcard/issues/158
Enables cutting a release with #123
Appears to be semver-clean, running `cargo semver-checks --default-features` and `--only-explicit-features`
=> revert 'Update heapless (#115)'

ci.sh, source/postcard/src/max_size.rs
Resolving #167 cc: @jamesmunns 
When building with, _e.g._, `--target riscv32i-unknown-none-elf` and `-F alloc` on the current main branch, the build will fail with 
```
error[E0432]: unresolved import `alloc::sync`
--> source/postcard/src/max_size.rs:5:33
|
5 | use alloc::{boxed::Box, rc::Rc, sync::Arc};
|                                 ^^^^ could not find `sync` in `alloc`
```
due to the lack of support on that target for atomic pointer operations (see: https://doc.rust-lang.org/alloc/sync/index.html).
Following the recommendation from the Rust docs, this gates definition of `POSTCARD_MAX_SIZE` for `alloc::sync::Arc` behind a configuration check to confirm it is available on the target first.
=> Check that target supports atomic pointer operations before defining max size for Arc

source/postcard/src/ser/serializer.rs
There is a broken link in the docs for the `Serializer`. The intended link seems to be to `crate::ser_flavors::Flavor`.
=> Corrected invalid link in `Serializer` docs

source/postcard-derive/src/schema.rs, source/postcard/Cargo.toml, source/postcard/src/lib.rs, source/postcard/src/schema.rs, source/postcard/tests/schema.rs
These types are use the heap to handle the recursive nature of schemas, and can be punned or converted with existing typed or serialized schema types.
For now, the serialized form is fairly inefficient: types and names are repeated instead of being interned or deduplicated in any way.
=> Implement a version of Schema types that are owned

source/postcard/src/accumulator.rs
Not strictly necessary, but makes `cargo test` pass when run without `heapless`.
=> Feature gate some tests

source/postcard-derive/Cargo.toml, source/postcard-derive/src/lib.rs, source/postcard-derive/src/schema.rs, source/postcard-schema/src/lib.rs
Closes #183
This only applies to `#[derive(Schema)]` (and not `#[derive(MaxSize)]`) because `MaxSize` seems likely to disappear soon (#179) and its trait lives in a different crate (`postcard::experimental::max_size` vs `postcard_schema`). If `MaxSize` ends up remaining as a derive macro and is moved to `postcard_schema`, this attribute can work with it as well.
The `syn` upgrade makes it possible to use [`parse_nested_meta()`](https://docs.rs/syn/2.0.89/syn/struct.Attribute.html#method.parse_nested_meta) for parsing attributes using the conventional structure of builtin attributes and is broken out into #185.
=> Add #[postcard(crate = ...)] attribute for derive(Schema)

ci.sh, source/postcard-schema/Cargo.toml, source/postcard-schema/src/impls/nalgebra_v0_33.rs
Closes #181, using a slice-of-array flattening function borrowed from the const-unstable [`<[[T; N]]>::as_flattened()`](https://doc.rust-lang.org/core/primitive.slice.html#method.as_flattened)
=> Fix nalgebra schema

source/postcard-schema/src/impls/builtins_nostd.rs, source/postcard/src/max_size.rs
Range, RangeInclusive, RangeFrom, RangeTo
=> Implement MaxSize for serializable Range structs

README.md
Add a section in the README warning about the use of serde attributes
=> docs: Add notes on serde attributes

source/postcard/src/de/flavors.rs
In `IOReader` and `EIOReader`, `pop()` does not properly handle EOF. The `read()` methods return `Ok(0)` when reaching the end of the file:
- https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read
- https://docs.rs/embedded-io/latest/embedded_io/trait.Read.html#tymethod.read
Switched to using `read_exact()`, which returns an `Err` if EOF is reached, which is what the code seems to expect.
=> Fix EOF not being handled correctly

ci.sh, source/postcard-schema/Cargo.toml, source/postcard-schema/src/key/hash.rs, source/postcard-schema/src/key/mod.rs, source/postcard-schema/src/lib.rs
This PR adds the `Key` type from postcard-rpc. I plan to use this type outside of postcard-rpc, and this allows for the ability to generate these tags without pulling in all of postcard-rpc.
=> Add `Key` from postcard-rpc

source/postcard-derive/src/schema.rs, source/postcard-dyn/src/de.rs, source/postcard-dyn/src/ser.rs, source/postcard-schema/src/impls/builtins_alloc.rs, source/postcard-schema/src/impls/builtins_nostd.rs, source/postcard-schema/src/impls/builtins_std.rs, source/postcard-schema/src/impls/chrono_v0_4.rs, source/postcard-schema/src/impls/heapless_v0_7.rs, source/postcard-schema/src/impls/heapless_v0_8.rs, source/postcard-schema/src/impls/mod.rs, source/postcard-schema/src/impls/nalgebra_v0_33.rs, source/postcard-schema/src/impls/uuid_v1_0.rs, source/postcard-schema/src/key/hash.rs, source/postcard-schema/src/key/mod.rs, source/postcard-schema/src/lib.rs, source/postcard-schema/src/schema/fmt.rs, source/postcard-schema/src/schema/mod.rs, source/postcard-schema/src/schema/owned.rs, source/postcard-schema/tests/schema.rs
Closes #196
This keeps the hashing behavior of ignoring struct/variant names, but these could be taken into account without sacrificing punning of vecs/slices/other seqs.
=> `postcard-schema`: restructure schema type hierarchy

source/postcard-schema/src/impls/builtins_alloc.rs, source/postcard-schema/src/impls/builtins_std.rs
This PR implements `Schema` for `alloc::borrow::Cow` and `std::alloc::Cow`, similarly to the existing implementations.
=> Implement `Schema` for `Cow`

source/postcard-schema/Cargo.toml, source/postcard-schema/src/impls/builtins_nostd.rs
Hedged my bets a bit here and added a feature to mask this out, but if that's not necessary it's a pretty easy fix.
=> Add impls for most `core::net` types.

source/postcard/src/accumulator.rs
The docs for `FeedResult::DeserError` say 
> Contains remaining section of input, if. any 
but it should be 
> Contains remaining section of input, if any.
=> Fix typo in docstring

source/postcard-schema/src/key/mod.rs
It doesn't seem to make sense to me as to why this is unsafe, when you have a safe constructor that takes an arbitrary string whose Key you could still use incorrectly. But also more importantly, `Key` implements `Deserialize` which means it is already possible to create abitrary keys via deserialization with arbitrary inputs.
So either this constructor ought to be safe, or `Key::for_path` needs to be also `unsafe` and the `Deserialize` impl has to be removed.
=> Mark `Key::from_bytes` as safe

source/postcard-schema/Cargo.toml, source/postcard-schema/src/impls/builtins_nostd.rs, source/postcard/Cargo.toml, source/postcard/src/max_size.rs
- `core::time::Duration`
- `core::marker::PhantomData`
- `core::num::{Wrapping,Saturating}`
- Added feature flags for `Saturating` since it's relatively new (1.74)
=> Implement Schema and MaxSize for more core types

source/postcard-schema-ng/src/impls/nalgebra_v0_33.rs, source/postcard-schema/src/impls/nalgebra_v0_33.rs, source/postcard/Cargo.toml, source/postcard/src/max_size.rs
MaxSize impls are gated under a new nalgebra-v0_33 feature flag for postcard analogous to the existing feature for postcard-schema.
=> Implement Schema and MaxSize for nalgebra::{Quaternion,Unit}

source/postcard/Cargo.toml
This adds back a "paste" feature that was removed in #222
cargo-semver-checks flags this as a semver compat issue.
=> Add dummy "paste" feature

Cargo.toml, source/postcard-derive-ng/Cargo.toml, source/postcard-derive-ng/src/max_size.rs, source/postcard2/Cargo.toml, source/postcard2/README.md, source/postcard2/src/accumulator.rs, source/postcard2/src/de/deserializer.rs, source/postcard2/src/de/flavors.rs, source/postcard2/src/de/mod.rs, source/postcard2/src/eio.rs, source/postcard2/src/error.rs, source/postcard2/src/fixint.rs, source/postcard2/src/lib.rs, source/postcard2/src/max_size.rs, source/postcard2/src/ser/flavors.rs, source/postcard2/src/ser/mod.rs, source/postcard2/src/ser/serializer.rs, source/postcard2/src/varint.rs, source/postcard2/tests/accumulator.rs, source/postcard2/tests/crc.rs, source/postcard2/tests/loopback.rs, source/postcard2/tests/max_size.rs
This clones postcard v1.1.2 into a new postcard2 crate, currently only with renamed everythings.
=> postcard2: Initial commit

source/postcard-derive/LICENSE-APACHE, source/postcard-derive/LICENSE-MIT, source/postcard-dyn/LICENSE-APACHE, source/postcard-dyn/LICENSE-MIT, source/postcard-schema/LICENSE-APACHE, source/postcard-schema/LICENSE-MIT, source/postcard/LICENSE-APACHE, source/postcard/LICENSE-MIT
Add symlinks to the top-level license files to fix missing license files in published crates.
Before:
```
[…]/source/postcard $ cargo publish --dry-run
[…]/source/postcard $  ls ../../target/package/postcard-1.1.1
Cargo.lock  Cargo.toml  Cargo.toml.orig  README.md  src  target  tests
```
After:
```
[…]/source/postcard $ cargo publish --dry-run
[…]/source/postcard $  ls ../../target/package/postcard-1.1.1
Cargo.lock  Cargo.toml  Cargo.toml.orig  LICENSE-APACHE  LICENSE-MIT  README.md  src  target  tests
```
Note that both chosen licenses require their text to be distributed.
=> Fix missing license files in published crates

source/postcard-schema-ng/src/impls/builtins_nostd.rs, source/postcard-schema/src/impls/builtins_nostd.rs
`Arguments<'_>` implements `Serialize` by collecting into a string: https://github.com/serde-rs/serde/blob/babafa54d283fb087fa94f50a2cf82fa9e582a7c/serde/src/ser/impls.rs#L62-L69
This works using this path of `postcard`: https://github.com/jamesmunns/postcard/blob/718aa6a6850456017c19eeff67303c633f875736/source/postcard/src/ser/serializer.rs#L320-L388
=> Implement Schema for Arguments

source/postcard/Cargo.toml, source/postcard/benches/varint_bench.rs, source/postcard/src/lib.rs, source/postcard/src/varint.rs
Make the varint serialization a little bit faster. Tested on my M2Max MacBook Pro:
```rust
varint_usize_small      time:   [448.37 ps 449.10 ps 449.95 ps]
change: [-2.9078% -2.6660% -2.4087%] (p = 0.00 < 0.05)
Performance has improved.
Found 15 outliers among 100 measurements (15.00%)
6 (6.00%) high mild
9 (9.00%) high severe
varint_usize_medium     time:   [859.93 ps 861.07 ps 862.44 ps]
change: [-24.991% -24.845% -24.696%] (p = 0.00 < 0.05)
Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
7 (7.00%) high mild
varint_usize_large      time:   [2.0006 ns 2.0037 ns 2.0071 ns]
change: [-41.360% -41.171% -40.984%] (p = 0.00 < 0.05)
Performance has improved.
Found 10 outliers among 100 measurements (10.00%)
6 (6.00%) high mild
4 (4.00%) high severe
varint_usize_zero …
```
=> Make varint serialization faster
